language: ruby

services:
  - docker

matrix:
  include:
    - env: UBUNTU=16.04 BUNDLE=deps ENV=py3 LINK=STATIC
    - env: UBUNTU=16.04 BUNDLE=deps ENV=py3 LINK=SHARED

script:
  - cd util/docker/open3d-test/tools
  - ./test.sh $UBUNTU $BUNDLE $ENV $LINK
  - ./stop.sh $UBUNTU $BUNDLE $ENV
