language: ruby
env:
  global:
    - SHARED=OFF
    - BUILD_DEPENDENCY_FROM_SOURCE=OFF
    - NPROC=2

notifications:
  email:
    on_success: never
    on_failure: always

matrix:

  include:
    # Build docs only
    - os: linux
      dist: bionic
      sudo: true
      language: python
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - doxygen
            - libosmesa6-dev
      before_install: ./util/scripts/setup-linux.sh
      script:
        - mkdir build
        - cd build
        - which python
        - python -V
        - pip install -U -q sphinx sphinx-rtd-theme
        - cmake -DPYTHON_EXECUTABLE=`which python` -DENABLE_HEADLESS_RENDERING=ON -DBUILD_GLEW=ON -DBUILD_GLFW=ON ..
        - make install-pip-package -j$NPROC
        - make -j$NPROC
        - bin/GLInfo
        - python -c "from open3d import *; import open3d; print(open3d)"
        - ../util/scripts/make-documentation.sh

