language: cpp
env:
  global:
    - SHARED=OFF
    - BUILD_DEPENDENCY_FROM_SOURCE=OFF
    - BUILD_TENSORFLOW_OPS=ON
    - NPROC=2

notifications:
  email:
    on_success: never
    on_failure: always

matrix:

  include:
    - os: osx
      osx_image: xcode11
      env: BUILD_TENSORFLOW_OPS=ON LOW_MEM_USAGE=ON
      #python@3 is python 3.7
      install:
        - brew update
        - brew upgrade python || true
        - ls /usr/local/opt
        - ls -l /usr/local/opt/*/bin/python
        - ls -l /usr/local/opt/python*/bin/
        - /usr/local/opt/python@3/bin/pip3 install virtualenv
        - /usr/local/opt/python@3/bin/python3 -m venv ~/py3env
        - source ~/py3env/bin/activate
        - echo $PATH
        - which python
        - which pip
        - pip install pytest
        - which pytest
        - nproc
        - ls -la ~/py3env/bin
        - pytest --version
        - ./util/scripts/install-deps-osx.sh
      script: ./util/scripts/run-travis.sh

    - os: osx
      osx_image: xcode11.5
      env: BUILD_TENSORFLOW_OPS=ON LOW_MEM_USAGE=ON
      install:
        - brew update
        - brew upgrade python || true
        - ls /usr/local/opt
        - ls -l /usr/local/opt/*/bin/python
        - ls -l /usr/local/opt/python*/bin/
        - /usr/local/opt/python@3/bin/pip3 install virtualenv
        - /usr/local/opt/python@3/bin/python3 -m venv ~/py3env
        - source ~/py3env/bin/activate
        - echo $PATH
        - which python
        - which pip
        - pip install pytest
        - which pytest
        - nproc
        - ls -la ~/py3env/bin
        - pytest --version
        - ./util/scripts/install-deps-osx.sh
      script: ./util/scripts/run-travis.sh

