language: cpp
env:
  global:
    - SHARED=OFF
    - BUILD_DEPENDENCY_FROM_SOURCE=OFF
    - BUILD_TENSORFLOW_OPS=ON
    - NPROC=2

notifications:
  email:
    on_success: never
    on_failure: always

matrix:

  include:
    # Default environment of macOS 10.13 High Sierra
    # compiled using clang shipped with xcode10.1
    - os: osx
      osx_image: xcode10.2
      env: BUILD_TENSORFLOW_OPS=OFF LOW_MEM_USAGE=ON
      install:
        - brew update
        - brew upgrade python || true
        - ls /usr/local/opt
        - ls -l /usr/local/opt/*/bin/python
        - PATH=/usr/local/opt/python@3.8/bin:$PATH
        - ./util/scripts/install-deps-osx.sh
      script: ./util/scripts/run-travis.sh

    - os: osx
      osx_image: xcode11.4
      env: BUILD_DEPENDENCY_FROM_SOURCE=ON BUILD_TENSORFLOW_OPS=OFF LOW_MEM_USAGE=ON
      install:
        - brew update
        - brew upgrade python || true
        - ls /usr/local/opt
        - ls -l /usr/local/opt/*/bin/python
        - PATH=/usr/local/opt/python@3.7/bin:$PATH
      script: ./util/scripts/run-travis.sh

    # - env: DOCKER=YES UBUNTU=16.04 BUNDLE=deps ENV=py3 LINK=STATIC
    #   script: ./util/docker/open3d-test/tools/test.sh $UBUNTU $BUNDLE $ENV $LINK
    #   install: sudo apt-get update && sudo apt-get install -y realpath

    # - env: DOCKER=YES UBUNTU=16.04 BUNDLE=deps ENV=py3 LINK=SHARED
    #   script: ./util/docker/open3d-test/tools/test.sh $UBUNTU $BUNDLE $ENV $LINK
    #   install: sudo apt-get update && sudo apt-get install -y realpath
