language: ruby
env:
  global:
    - SHARED=OFF
    - BUILD_DEPENDENCY_FROM_SOURCE=OFF
    - NPROC=2

notifications:
  email:
    on_success: never
    on_failure: always

matrix:

  include:
    - os: osx
      osx_image: xcode10.2
      before_install:
        - ./util/scripts/install-deps-osx.sh
      script: travis_wait 90 ./util/scripts/run-travis.sh

    # - os: osx
    #   osx_image: xcode10.2
    #   env: BUILD_DEPENDENCY_FROM_SOURCE=ON
    #   script: travis_wait 90 ./util/scripts/run-travis.sh
