os: osx

before_install:
  - brew update > /dev/null 2>&1
  - brew upgrade python > /dev/null 2>&1
  - sudo rm -f /usr/local/include/c++
  - brew install gcc5 --without-multilib
  - brew install libomp
  - ./util/scripts/install-deps-osx.sh > /dev/null 2>&1
  - gcc --version && cmake --version && python -V

script:
  - mkdir build && cd build
  - cmake -DOpenMP_C_FLAGS="-fopenmp=libomp" -DOpenMP_C_LIB_NAMES="libomp" -DOpenMP_libomp_LIBRARY=/usr/local/opt/libomp/lib/libomp.dylib -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include" -DOpenMP_CXX_LIB_NAMES="omp" -DOpenMP_omp_LIBRARY=/usr/local/opt/libomp/lib/libomp.dylib ../src/
  - make
