language: ruby

services:
  - docker

matrix:
  include:
    - script: ~/open3d/util/docker/open3d-test/tools/test.sh 16.04 deps py3 STATIC
    - script: ~/open3d/util/docker/open3d-test/tools/test.sh 16.04 deps py3 SHARED
