language: cpp
arch: arm64
os: linux
dist: focal
sudo: true
language: python
python: "3.7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - apt-utils
      - autoconf
      - build-essential
      - ccache
      - clang-7
      - git
      - libblas-dev
      - libc++-7-dev
      - libc++abi-7-dev
      - libglu1-mesa-dev
      - liblapack-dev
      - liblapacke-dev
      - libosmesa6-dev
      - libsdl2-dev
      - libtbb-dev
      - libtool
      - libudev-dev
      - libxi-dev
      - ninja-build
      - python3-dev
      - wget
      - xorg-dev
install:
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-7 100
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-7 100
  - sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
  - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
  - >
    python -m pip install -U
    pip=="20.2.4"
    wheel=="0.35.1"
    setuptools=="50.3.2"
    yapf=="0.30.0"
    pytest=="6.0.1"
    scipy=="1.5.4"
    wheel=="0.35.1"
  - wget https://github.com/Kitware/CMake/releases/download/v3.19.7/cmake-3.19.7-Linux-aarch64.tar.gz
  - tar -xvf cmake-3.19.7-Linux-aarch64.tar.gz
  - cp -ar cmake-3.19.7-Linux-aarch64 ${HOME}
script:
  - PATH=${HOME}/cmake-3.19.7-Linux-aarch64/bin:$PATH
  - which cmake
  - cmake --version
  - pwd
  - mkdir build
  - cd build
  - >
    cmake
    -DUSE_BLAS=ON
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_SHARED_LIBS=ON
    -DBUILD_GUI=ON
    -DCMAKE_C_COMPILER=gcc
    -DCMAKE_CXX_COMPILER=g++
    -DBUILD_FILAMENT_FROM_SOURCE=ON
    -DBUILD_TENSORFLOW_OPS=OFF
    -DBUILD_PYTORCH_OPS=OFF
    -DBUILD_UNIT_TESTS=ON
    -DCMAKE_INSTALL_PREFIX=~/open3d_install
    -DPYTHON_EXECUTABLE="$(which python3)"
    ..
  - echo "cmake config done"
  - make -j$(nproc)
  - make tests -j$(nproc)
  - make install-pip-package -j$(nproc)
  - ./bin/tests --gtest_filter="-*Reduce*Sum*"
  - pytest ../python/test/ --ignore ../python/test/ml_ops/ --ignore ../python/test/t/io/test_realsense.py

