language: ruby

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y realpath

matrix:
  include:
    - env: UBUNTU=16.04 BUNDLE=deps ENV=py3 LINK=STATIC
    - env: UBUNTU=16.04 BUNDLE=deps ENV=py3 LINK=SHARED

script:
  - ./util/docker/open3d-test/tools/test.sh $UBUNTU $BUNDLE $ENV $LINK
