name: Default reconstruction system config

# General parameters.
device: CUDA:0
engine: tensor
multiprocessing: false
debug_mode: true

# Path to input data.
path_dataset: ''
depth_folder: depth
color_folder: color
path_intrinsic: ''
path_color_intrinsic: ''

# RGB-D input related parameters.
depth_min: 0.1
depth_max: 3.0
depth_scale: 1000.0

# RGB-D registation related parameters.
fragment_size: 100
odometry_method: hybrid
odometry_loop_interval: 10
odometry_loop_weight: 0.1
odometry_distance_thr: 0.07

# Point-cloud fragments registration related parameters.
icp_method: colored
icp_voxelsize: 0.05
icp_distance_thr: 0.07
global_registration_method: ransac
registration_loop_weight: 0.1

# TSDF integration related parameters.
integration_mode: color
voxel_size: 0.0058
trunc_voxel_multiplier: 8.0
block_count: 30000
est_point_count: 4000000
surface_weight_thr: 3.0
