name: macOS CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]  # Rebuild on new pushes to PR

jobs:
  macos:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        BUILD_ML_OPS: [ON, OFF]
    env:
      SHARED: OFF
      NPROC: 2
      BUILD_CUDA_MODULE: OFF
      BUILD_TENSORFLOW_OPS: ${{ matrix.BUILD_ML_OPS }}
      BUILD_PYTORCH_OPS: ${{ matrix.BUILD_ML_OPS }}
      LOW_MEM_USAGE: ON
      BUILD_RPC_INTERFACE: ON
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup cache
        uses: actions/cache@v2
        with:
          # Ref: https://github.com/apache/incubator-mxnet/pull/18459/files
          path: ~/.ccache
          # We include the commit sha in the cache key, as new cache entries are
          # only created if there is no existing entry for the key yet.
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          # Restore any ccache cache entry, if none for
          # ${{ runner.os }}-ccache-${{ github.sha }} exists.
          # Common prefix will be used so that ccache can be used across commits.
          restore-keys: |
            ${{ runner.os }}-ccache
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          ./util/install_deps_macos.sh skip-upgrade
          brew install ccache
          ccache -M 2G  # GitHub's total cache limit is 5GB for all OSes.
      - name: Config and build
        run: |
          PATH=/usr/local/var/homebrew/linked/ccache/libexec:$PATH
          ccache -s
          ./util/run_ci.sh
          ccache -s


  build-macos-wheel:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.5, 3.6, 3.7, 3.8]
    env:
      BUILD_CUDA_MODULE: OFF
      BUILD_PYTORCH_OPS: ON
      NPROC: 2
      LOW_MEM_USAGE: ON
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup cache
        uses: actions/cache@v2
        with:
          # Ref: https://github.com/apache/incubator-mxnet/pull/18459/files
          path: ~/.ccache
          # We include the commit sha in the cache key, as new cache entries are
          # only created if there is no existing entry for the key yet.
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          # Restore any ccache cache entry, if none for
          # ${{ runner.os }}-ccache-${{ github.sha }} exists.
          # Common prefix will be used so that ccache can be used across commits.
          restore-keys: |
            ${{ runner.os }}-ccache
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          ./util/install_deps_macos.sh skip-upgrade
          brew install ccache
          ccache -M 2G  # GitHub's total cache limit is 5GB for all OSes.

      - name: Config and build
        run: |
          PATH=/usr/local/var/homebrew/linked/ccache/libexec:$PATH
          ccache -s
          ./util/build_wheel.sh
          ccache -s
          echo "::set-env name=PIP_PKG_NAME::$(basename build/lib/python_package/pip_package/open3d*.whl)"

      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: open3d_macosx_x86_64_wheels
          path: build/lib/python_package/pip_package/${{ env.PIP_PKG_NAME }}
          if-no-files-found: error

  test-macos-wheel:
    name: Test macos wheel
    runs-on: macos-10.15
    needs: [build-macos-wheel]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: false
      - name: Download wheels
        uses: actions/download-artifact@v2
        # See https://github.com/dawidd6/action-download-artifact for more
        # flexible artifact download options
        with:
          name: open3d_macosx_x86_64_wheels

      - name: Set up Python 3.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.5
      - name: Test Python 3.5 package
        run: |
          python -V
          python3.5 -m pip install open3d*cp35*.whl
          python3.5 -c "import open3d; print(open3d)"
          python3.5 -c "import open3d; open3d.pybind.core.kernel.test_mkl_integration()"
          python3.5 -c "import open3d; print('CUDA enabled: ', open3d.__cuda__)"
      - name: Set up Python 3.6
        if: ${{ !cancelled() }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Test Python 3.6 package
        if: ${{ !cancelled() }}
        run: |
          python -V
          python3.6 -m pip install open3d*cp36*.whl
          python3.6 -c "import open3d; print(open3d)"
          python3.6 -c "import open3d; open3d.pybind.core.kernel.test_mkl_integration()"
          python3.6 -c "import open3d; print('CUDA enabled: ', open3d.__cuda__)"
      - name: Set up Python 3.7
        if: ${{ !cancelled() }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Test Python 3.7 package
        if: ${{ !cancelled() }}
        run: |
          python -V
          python3.7 -m pip install open3d*cp37*.whl
          python3.7 -c "import open3d; print(open3d)"
          python3.7 -c "import open3d; open3d.pybind.core.kernel.test_mkl_integration()"
          python3.7 -c "import open3d; print('CUDA enabled: ', open3d.__cuda__)"
      - name: Set up Python 3.8
        if: ${{ !cancelled() }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Test Python 3.8 package
        if: ${{ !cancelled() }}
        run: |
          python -V
          python3.8 -m pip install open3d*cp38*.whl
          python3.8 -c "import open3d; print(open3d)"
          python3.8 -c "import open3d; open3d.pybind.core.kernel.test_mkl_integration()"
          python3.8 -c "import open3d; print('CUDA enabled: ', open3d.__cuda__)"
