name: Ubuntu CUDA GCloud CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    env:
      DEVELOPER_BUILD: ON
      PYTHON_VERSION: 3.6
      CCACHE_TAR_NAME: open3d-ubuntu-2004-cuda-gcloud-ci-ccache
    steps:
      - name: Cancel outdated
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
      # - name: Maximize build space
      #   run: |
      #     source util/ci_utils.sh
      #     maximize_ubuntu_github_actions_build_space
      - name: Docker build
        run: |
          .github/workflows/docker_build.sh 2-bionic
