name: Ubuntu CUDA GCloud CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    env:
      DEVELOPER_BUILD: ON
      PYTHON_VERSION: 3.6
      CCACHE_TAR_NAME: open3d-ubuntu-2004-cuda-gcloud-ci-ccache
    steps:
      # - name: Cancel outdated
      #   uses: fkirc/skip-duplicate-actions@master
      #   with:
      #     github_token: ${{ github.token }}
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: GCloud CLI setup
        uses: google-github-actions/setup-gcloud@master
        with:
          version: ${{ env.GCE_CLI_GHA_VERSION }}
          service_account_key: ${{ secrets.GCE_SA_KEY_GPU_CI }}
          project_id: ${{ secrets.GCE_PROJECT }}
      - name: GCloud CLI authenticate
        run: |
          gcloud auth configure-docker
          gcloud info
      # - name: Maximize build space
      #   run: |
      #     source util/ci_utils.sh
      #     maximize_ubuntu_github_actions_build_space
      - name: Docker build
        run: |
          .github/workflows/docker_build.sh 2-bionic
      - name: Docker push
        run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          DOCKER_TAG=open3d-ubuntu-cuda-gcloud-ci:2-bionic-${GIT_HASH}
          GCLOUD_DOCKER_TAG=gcr.io/${{ secrets.GCE_PROJECT }}/${DOCKER_TAG}
          docker image tag ${DOCKER_TAG} ${GCLOUD_DOCKER_TAG}
          docker push ${GCLOUD_DOCKER_TAG}
      - name: VM create
        run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          VM_NAME=open3d-ubuntu-cuda-gcloud-ci-2-bionic-${GIT_HASH}
          gcloud compute instances create ${VM_NAME} \
            --project open3d-dev \
            --service-account="${{ secrets.GCE_GPU_CI_SA }}" \
            --image-family common-cu110 \
            --image-project deeplearning-platform-release \
            --zone=australia-southeast1-a \
            --accelerator="count=2,type=nvidia-tesla-t4" \
            --maintenance-policy=TERMINATE \
            --machine-type=n1-standard-4 \
            --metadata "install-nvidia-driver=True,proxy-mode=project_editors" \
            --boot-disk-type=pd-ssd
          sleep 90s # Wait for nvidia driver installation
      - name: VM Docker run
        run: |
          gcloud compute ssh ${VM_NAME} \
            --zone=australia-southeast1-a \
            --command "nvidia-smi"
          gcloud compute ssh ${VM_NAME} \
            --zone=australia-southeast1-a \
            --command "sudo docker run -it --rm ${GCE_DOCKER_TAG} cat hello.txt"
      - name: VM delete
        if: always()
        run: |
          gcloud compute instances delete ${VM_NAME} \
            --zone=australia-southeast1-a \
            --quiet
      - name: Docker delete
        if: always()
        run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          DOCKER_TAG=open3d-ubuntu-cuda-gcloud-ci:2-bionic-${GIT_HASH}
          GCLOUD_DOCKER_TAG=gcr.io/${{ secrets.GCE_PROJECT }}/${DOCKER_TAG}
          docker push ${GCLOUD_DOCKER_TAG}
          gcloud container images delete ${GCLOUD_DOCKER_TAG}
