name: Ubuntu CUDA GCloud CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    env:
      DEVELOPER_BUILD: ON
      PYTHON_VERSION: 3.6
      CCACHE_TAR_NAME: open3d-ubuntu-2004-cuda-gcloud-ci-ccache
    steps:
      # - name: Cancel outdated
      #   uses: fkirc/skip-duplicate-actions@master
      #   with:
      #     github_token: ${{ github.token }}
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: GCloud CLI setup
        uses: google-github-actions/setup-gcloud@master
        with:
          version: ${{ env.GCE_CLI_GHA_VERSION }}
          service_account_key: ${{ secrets.GCE_SA_KEY_GPU_CI }}
          project_id: ${{ secrets.GCE_PROJECT }}
      # - name: Maximize build space
      #   run: |
      #     source util/ci_utils.sh
      #     maximize_ubuntu_github_actions_build_space
      - name: Set container and vm names in GITHUB_ENV
        run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          DOCKER_TAG=open3d-ubuntu-cuda-gcloud-ci:2-bionic-${GIT_HASH}
          GCLOUD_DOCKER_TAG=gcr.io/${{ secrets.GCE_PROJECT }}/${DOCKER_TAG}
          VM_NAME=open3d-ubuntu-cuda-gcloud-ci-2-bionic-${GIT_HASH}
          echo "GIT_HASH=${GIT_HASH}"                   >> $GITHUB_ENV
          echo "DOCKER_TAG=${DOCKER_TAG}"               >> $GITHUB_ENV
          echo "GCLOUD_DOCKER_TAG=${GCLOUD_DOCKER_TAG}" >> $GITHUB_ENV
          echo "VM_NAME=${VM_NAME}"                     >> $GITHUB_ENV
      - name: Docker build
        run: |
          .github/workflows/docker_build.sh 2-bionic
      - name: Docker push
        run: |
          gcloud auth configure-docker
          docker image tag ${{ env.DOCKER_TAG }} ${{ env.GCLOUD_DOCKER_TAG }}
          docker push ${{ env.GCLOUD_DOCKER_TAG }}
      - name: VM create
        run: |
          .github/workflows/create_gcloud_vm.sh
      - name: VM Docker run
        run: |
          gcloud compute ssh ${{ env.VM_NAME }} \
            --zone=australia-southeast1-a \
            --command "sudo docker run -i --rm ${{ env.GCLOUD_DOCKER_TAG}} cat hello.txt"
      - name: VM delete
        if: always()
        run: |
          gcloud compute instances delete ${{ env.VM_NAME }} \
            --zone=australia-southeast1-a \
            --quiet
      - name: Docker delete
        if: always()
        run: |
          docker push ${{ env.GCLOUD_DOCKER_TAG}}
          gcloud container images delete ${{ env.GCLOUD_DOCKER_TAG}}
